baseURL = "https://knr.edu.pl/"
languageCode = "pl-pl"
title = "Koło Naukowe Robotyków PW"

[markup.goldmark.renderer]
unsafe= true

[project]
title = "Project"
singular = "project"
plural = "projects"

[article]
title = "Artykuł"
singular = "article"
plural = "articles"
